declare namespace NodeJS {
  interface ProcessEnv {
    SOURCE_STORAGE_REGION: string
    SOURCE_STORAGE_ENDPOINT: string
    SOURCE_STORAGE_ACCESS_KEY_ID: string
    SOURCE_STORAGE_SECRET_ACCESS_KEY: string
    SOURCE_BUCKET: string
    DESTINATION_STORAGE_REGION: string
    DESTINATION_STORAGE_ENDPOINT: string
    DESTINATION_STORAGE_ACCESS_KEY_ID: string
    DESTINATION_STORAGE_SECRET_ACCESS_KEY: string
    DESTINATION_BUCKET: string
  }
}
